apiVersion: v1
kind: Service
metadata:
  name: nlb-pod-service
  labels:
    app: pod-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: Loadbalancer
  selector: 
    app: nginx-pod
  ports:
    - name: pod-port
      port: 80
      targetPort: 80