apiVersion: v1
kind: Service
metadata:
  name: pod-service
  labels:
    app: pod-service
spec:
  type: NodePort
  selector: 
    app: nginx-pod
  ports:
    - name: pod-port
      port: 80
      targetPort: 80
      nodePort: 30003